### ISSUE TITLE
Update API and dashboard ingress route as part of domain configuration

### ISSUE THREAD

**Issue by mohamed-abdelrhman** [kotalco/core-api#168]
Update API and dashboard ingress route while the user is setting domain, so that user can access dashboard and api using the domain, instead of Traefik load-balancer ip address.

* fetch ingress route by name `kotal-stack` in `kotal` namespace
* you will find 2 routes
  * one for the API `/api`
  * one for the dashboard `/` 
* for each route:
  *  update the match `spec.routes[n].match` with the new domain `Host(domain)`
  * if route already have a domain, replace `Host(oldDomain)` with the `Host(newDomain)`
* update entry point to be web secure
* update the ingress route to use tis resolver
```yaml
tls:
    certResolver: myresolver
```

Example (before the update)
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kotal-stack
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: kotal-dashboard
          port: 3000
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: kotal-api
          port: 6000
```

After the update with kotal.com domain

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kotal-stack
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kotal.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: kotal-dashboard
          port: 3000
    - match: Host(`kotal.com`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: kotal-api
          port: 6000
  tls:
    certResolver: myresolver
```
